// <auto-generated />
using System;
using FIlghtBookingSystemAspWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIlghtBookingSystemAspWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240711065010_md")]
    partial class md
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIlghtBookingSystemAspWebApi.Models.BookingDetails", b =>
                {
                    b.Property<int>("Booking_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Flight_ID")
                        .HasColumnType("int");

                    b.Property<int>("No_of_passengers")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<int>("User_ID1")
                        .HasColumnType("int");

                    b.HasKey("Booking_Id");

                    b.HasIndex("User_ID1");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("FIlghtBookingSystemAspWebApi.Models.CheckInStatus", b =>
                {
                    b.Property<int>("Check_in_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Check_in_Id"));

                    b.Property<int>("BookingDetailsBooking_Id")
                        .HasColumnType("int");

                    b.Property<int>("Booking_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Check_in_Status")
                        .HasColumnType("bit");

                    b.Property<int>("Flight_ID")
                        .HasColumnType("int");

                    b.Property<string>("Seat_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Check_in_Id");

                    b.HasIndex("BookingDetailsBooking_Id");

                    b.ToTable("CheckInStatuses");
                });

            modelBuilder.Entity("FIlghtBookingSystemAspWebApi.Models.FlightDetails", b =>
                {
                    b.Property<int>("Flight_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Flight_ID"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Arrival_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departure_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total_Seats")
                        .HasColumnType("int");

                    b.HasKey("Flight_ID");

                    b.ToTable("FlightDetails");
                });

            modelBuilder.Entity("FIlghtBookingSystemAspWebApi.Models.Passenger", b =>
                {
                    b.Property<int>("Passenger_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Passenger_Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("BookingDetailsBooking_Id")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Passenger_Id");

                    b.HasIndex("BookingDetailsBooking_Id");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("FIlghtBookingSystemAspWebApi.Models.UserTable", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Phone_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("UserTables");
                });

            modelBuilder.Entity("FIlghtBookingSystemAspWebApi.Models.BookingDetails", b =>
                {
                    b.HasOne("FIlghtBookingSystemAspWebApi.Models.UserTable", "User")
                        .WithMany()
                        .HasForeignKey("User_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIlghtBookingSystemAspWebApi.Models.CheckInStatus", b =>
                {
                    b.HasOne("FIlghtBookingSystemAspWebApi.Models.BookingDetails", "BookingDetails")
                        .WithMany()
                        .HasForeignKey("BookingDetailsBooking_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("FIlghtBookingSystemAspWebApi.Models.Passenger", b =>
                {
                    b.HasOne("FIlghtBookingSystemAspWebApi.Models.BookingDetails", null)
                        .WithMany("Passengers")
                        .HasForeignKey("BookingDetailsBooking_Id");
                });

            modelBuilder.Entity("FIlghtBookingSystemAspWebApi.Models.BookingDetails", b =>
                {
                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
